# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/yazi.json"

[manager]
sort_sensitive = true
linemode = "size"

[preview]
image_filter = "triangle"
image_quality = 75
sixel_fraction = 15
ueberzug_scale = 1
ueberzug_offset = [0, 0, 0, 0]

[opener]
edit = [
  { exec = 'wezterm start -- nvim "$@"', desc = "nvim", block = true, for = "unix", orphan = true },
  { exec = 'code "%*"', orphan = true, for = "windows" },
]
open = [
  { exec = 'open "$@"', desc = "Open", for = "linux" },
  { exec = 'open "$@"', desc = "Open", for = "macos" },
  { exec = 'start "" "%1"', orphan = true, desc = "Open", for = "windows" },
]
reveal = [
  { exec = 'open -R "$1"', desc = "Reveal", for = "macos" },
  { exec = 'explorer /select, "%1"', orphan = true, desc = "Reveal", for = "windows" },
  { exec = '''exiftool "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show EXIF", for = "unix" },
]
extract = [
  { exec = 'unar "$1"', desc = "Extract here", for = "unix" },
  { exec = 'unar "%1"', desc = "Extract here", for = "windows" },
]
play = [
  { exec = 'mpv "$@"', orphan = true, for = "unix" },
  { exec = 'videocut "$@"', orphan = true, for = "unix" },
  { exec = 'mpv "%1"', orphan = true, for = "windows" },
  { exec = '''mediainfo "$1"; echo "Press enter to exit"; read''', block = true, desc = "Show media info", for = "unix" },
]


[input]
# cd
cd_offset = [0, 18, 50, 3]

# create
create_offset = [0, 18, 50, 3]

# trash
trash_offset = [0, 18, 50, 3]

# delete
delete_offset = [0, 18, 50, 3]

# filter
filter_offset = [0, 18, 50, 3]

# find
find_offset = [0, 18, 50, 3]

# search
search_offset = [0, 18, 50, 3]

# shell
shell_offset = [0, 18, 50, 3]

# overwrite
overwrite_offset = [0, 18, 50, 3]

# quit
quit_offset = [0, 18, 50, 3]
